# Generated by Django 2.1.7 on 2019-04-25 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20190328_0515'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='img_url',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
