# Generated by Django 2.1.7 on 2019-03-09 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190309_1945'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmark',
            old_name='User',
            new_name='user',
        ),
    ]
