# Generated by Django 2.1.7 on 2019-07-09 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20190709_0244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='user',
        ),
    ]
