# Generated by Django 2.1.7 on 2019-04-25 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_bookmark_img_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='image',
        ),
    ]
