# Generated by Django 2.1.7 on 2019-04-25 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_bookmark_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='memo',
            field=models.TextField(blank=True),
        ),
    ]
